version: "3.9"

services:
  nextjs:
    container_name: gifts-nextjs
    build:
      context: .
      # Path to the Dockerfile inside .docker/next directory
      dockerfile: .docker/next/Dockerfile
    ports:
      - 3002:3002
    volumes:
      - ./nextjs:/app
      - /app/node_modules

  # Add more services here
  # Create new service for nestjs based on Dockerfile in .docker/nest directory
  nestjs:
    container_name: gifts-nestjs
    build:
      context: .
      dockerfile: .docker/nest/Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ./nestjs:/app
      - /app/node_modules