import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import './globals.css'
import LayoutProvider from '@/app/components/LayoutProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: any) {
  const locale = await getLocale()
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={`${inter.className} login-container bg-login-bg-gradient w-screen h-screen`}>
        <NextIntlClientProvider messages={messages}>
          <LayoutProvider>{props.children}</LayoutProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
