import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import './globals.css'
import LayoutProvider from '@/app/components/layouts/LayoutProvider'
import Header from '@/app/components/layouts/Header'
import Footer from '@/app/components/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: any) {
  const locale = await getLocale()
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body
        className={`${inter.className} login-container bg-login-bg-gradient bg-no-repeat bg-cover bg-center relative min-h-screen h-[100%]`}
      >
        <NextIntlClientProvider messages={messages}>
          <Header />
          <LayoutProvider>{props.children}</LayoutProvider>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
